name: Update Nums in README

on:
  schedule:
    - cron: "*/5 * * * *"  # 5분마다 숫자 새로고침
  workflow_dispatch:  # 수동 실행 가능

permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: 리포지토리 체크아웃
        uses: actions/checkout@v3

      - name: Python 설치
        uses: actions/setup-python@v3
        with:
          python-version: "3.x"

      - name: 새로운 year number 설정
        run: |
          pip install requests
          python update_numbers.py


      - name: 변경 사항 커밋 및 푸시
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "숫자정보 갱신" || echo "No changes to commit"
          git push